swagger: "2.0"
info:
  title: Argent Bank - Transactions API documentation
  description: Contains all available transactions API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /accounts/{accountId}/transactions:
    parameters:
      - name: accountId
        in: path
        required: true
        type: string
        description: ID of the account that needs to be fetched
    get:
      tags:
        - Transactions
      summary: Returns all transactions
      description: API for fetching all transactions, optionally filtered by date
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: query
          name: startDate
          type: string
          format: date
          description: Start date for filtering transactions (e.g., 2025-04-01)
          required: true
        - in: query
          name: endDate
          type: string
          format: date
          description: End date for filtering transactions (e.g., 2025-04-30)
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transactions fetched Successfully
          schema:
            $ref: "#/definitions/Transactions"
        "401":
          description: Unauthorized – Missing or invalid JWT token
        "404":
          description: Account not found
        "500":
          description: Internal Server Error
  /accounts/{accountId}/transactions/{transactionId}:
    parameters:
      - name: accountId
        in: path
        required: true
        type: string
        description: ID of the account that needs to be fetched
    get:
      tags:
        - Transactions
      summary: Find transaction by ID
      description: Get transaction details by ID
      operationId: getTransactionById
      parameters:
        - name: transactionId
          in: path
          description: ID of transaction that needs to be fetched
          required: true
          type: integer
          format: int64
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      responses:
        "200":
          description: Transaction fetched successfully
          schema:
            $ref: "#/definitions/TransactionRequest"
        "401":
          description: Unauthorized – Missing or invalid JWT token
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    patch:
      tags:
        - Transactions
      summary: Update transaction
      description: Update a transaction
      parameters:
        - name: transactionId
          in: path
          description: ID of transaction that needs to be updated
          required: true
          type: integer
          format: int64
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction
          required: true
          schema:
            $ref: "#/definitions/TransactionRequest"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized – Missing or invalid JWT token
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        $ref: "#/definitions/TransactionRequest"
  Transactions:
    type: array
    items:
      $ref: "#/definitions/TransactionRequest"
  TransactionRequest:
    type: object
    properties:
      id:
        type: integer
        format: int64
      date:
        type: string
        format: date-time
      description:
        type: string
      amount:
        type: number
        format: float
      balance:
        type: number
        format: float
      type:
        type: string
      category:
        type: string
        enum: [Food, Rent, Income, Entertainment, Travel]
      notes:
        type: string
        maxLength: 500
